export const InternetHeaderConstants = {
  ethernet_frame_length: 14,
  ipv4_length: 20,
  ipv4_checksum_offset: 10,
  ipv4_checksum_length: 2,
  ipv4_src_ip_offset: 12,
  ipv4_dest_ip_offset: 16,
  ipv6_length: 40,
  ipv6_src_ip_offset: 8,
  ipv6_dest_ip_offset: 24,
  udp_length: 8,
  udp_checksum_offset: 6,
  udp_checksum_length: 2,
  tcp_length: 20,
  tcp_checksum_offset: 16,
  tcp_checksum_length: 2,
};
