name: Deploy to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install Yarn dependencies
        run: yarn
      - name: Run Linter
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Build
        run: yarn build
        env:
          VITE_COMMIT_SHA: ${{ github.sha }}
          VITE_REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
      - name: Upload build files for deployment
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build files for deployment
        uses: actions/download-artifact@v4
        with:
          name: deployment-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
