name: Test CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: Install Yarn dependencies
        run: yarn
      - name: Run Linter
        run: yarn lint
      - name: Run Tests
        run: yarn test
